### PR TITLE
Collapse Panel and Collapse Group

### PR DESCRIPTION
**Pull request by june-tran**
Major: Added Collapse Panel and Collapse Group. 
(Very) Minor: Fixed UI of Add Cube button.

Basic Scene file is only used for Testing and Showcasing. Please don't merge it to Main.

### CODE REVIEW

**Review by notalfredo — COMMENTED** [review]
Looks good to me can you just remove the basicScene.tsx from the changes ?

**Review by notalfredo — DISMISSED** [review]

**Comment by notalfredo** [comment]
image

this happens when I try to add a group dynamically, 

so if I add the following while the program is running
```html
        <group>
           <TestBox/>
           <TestBox/>
           <TestBox/>
           <TestBox/>
           <TestBox/>
           <TestBox/>
        </group>
```

Then the program gives me that error message

**Comment by june-tran** [comment]
Did you get that error message when you reload the page or when you click on a button on the page?
Seems to work on mine? 

Screenshot 2023-09-19 at 3 33 27 PM

**Comment by notalfredo** [comment]
> Did you get that error message when you reload the page or when you click on a button on the page? Seems to work on mine?
> 
> Screenshot 2023-09-19 at 3 33 27 PM

I get it when I add the code earlier shown and just save. If I reload the page it works fine. But it breaks when you save and not reload. (that should not happen)

**Comment by june-tran** [comment]
Yeah I just tried and saw the error now. Let me look into it

**Review by notalfredo — COMMENTED** [review]
Looks good ! Just one thing that I noticed while playing around 
image

when I have the panel collapsed if I try to either rotate/zoom/pan in the purple area it wont let me. Could you look into that ? Otherwise its great ! Im going to go ahead and merge the branch when you acknowledge this. Could you work on fixing that issue next ? ?

**Comment by june-tran** [comment]
I just fixed it. It worked on my side now. Let me know if it works for you.

**Review by notalfredo — APPROVED** [review]

**Pull request merged**
